---
- name: Enable cgroups
  become: true
  tags:
    - worker
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regex: '^((?:(?!cgroup_memory=1).)*)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    backrefs: yes
    state: present

- name: Get External HDD UUID
  register: lsblk
  ansible.builtin.shell: "lsblk -o UUID /dev/sda1 | grep -v UUID"

- name: Update fstab
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    search_string: /nfs
    line: UUID={{ lsblk.stdout }} /nfs ntfs defaults 0 0
    state: present

- name: Download Node-Exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-arm64.tar.gz
    dest: /home/hal/node_exporter.tar.gz

- name: Install Node-Exporter
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: /home/hal/node_exporter.tar.gz
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1

- name: Create Node-Exporter Service
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/nodeexporter.service
    content: |
      [Unit]
        Description=Node-Exporter

        [Service]
        TimeoutStartSec=0
        ExecStart=/usr/local/bin/node_exporter

        [Install]
        WantedBy=multi-user.target

- name: Start Node-Exporter Service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: nodeexporter
    enabled: true
    state: started

- name: Create directory for Docker GPG key
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
      signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker
    state: present

- name: Install Docker and related packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add Docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable and start Docker services
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service

- name: Install microk8s
  tags:
    - worker
  ansible.builtin.include_role:
    name: istvano.microk8s

- name: Reboot
  become: true
  tags:
    - worker
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: Create Grafana path
  ansible.builtin.file:
    path: /nfs/grafana
    state: directory

- name: Create MySQL path
  ansible.builtin.file:
    path: /nfs/mysql
    state: directory

- name: Create Registry path
  ansible.builtin.file:
    path: /nfs/registry
    state: directory
