api:
	ansible-playbook -vJK api.yml

build:
	ansible-playbook -vJK build.yml

cleanup:
	ansible-playbook -vJK cleanup_microk8s.yml

database:
	ansible-playbook -vJ database.yml

k8s:
	ansible-playbook -vJK kubernetes.yml

migrations:
	ansible-playbook -vJ migrations.yml

monitoring:
	ansible-playbook -vJ monitoring.yml

storage:
	ansible-playbook -vJ storage.yml
