build:
	ansible-playbook -vK build.yml

database:
	ansible-playbook -vJK database.yml

k8s:
	ansible-playbook -vJK kubernetes.yml

migrations:
	ansible-playbook -vJK migrations.yml

monitoring:
	ansible-playbook -v monitoring.yml

storage:
	ansible-playbook -v storage.yml
